added win 64 ci build

diff --git a/fftools/Makefile b/fftools/Makefile
--- a/fftools/Makefile
+++ b/fftools/Makefile
@@ -2,7 +2,8 @@ SRC_PATH=../
 CC=clang
 ARCH=arm64
 C_FILES=ffplay.c cmdutils.c patch/*.c patch/AudioCompress/*.c patch/Osd/*.c patch/video_normalizer/*.c patch/bitrate_bar/*.c
-OUT_FILE=ffpatched # TODO: use subfolder
+OUT_DIR=ffpatched_$(ARCH)
+OUT_FILE=ffpatched
 CONFIG_PARAMS=--enable-gpl --disable-ffmpeg --disable-ffprobe --disable-avdevice --disable-avcodec --disable-avformat --disable-swresample --disable-swscale --disable-postproc --disable-avfilter --arch=${ARCH} # --enable-libx264
 FFMPEG_LIBS=-lavformat -lavcodec -lavfilter -lavdevice -lavutil -lswresample -lswscale
 TEST_STREAM="http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8"
@@ -11,8 +12,8 @@ TEST_STREAM="http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8"
 
 #unix  compile scripts
 all:
-	$(MAKE) libavutil/ffversion.h
 	$(MAKE) clean
+	$(MAKE) libavutil/ffversion.h
 	$(MAKE) config
 	$(MAKE) build
 	$(MAKE) test
@@ -31,17 +32,18 @@ libavutil/ffversion.h .version:
 # make
 config:
 	cd $(SRC_PATH) && ./configure --cc=$(CC) $(CONFIG_PARAMS)
+	mkdir -p $(OUT_DIR)
 
 build:
-	$(CC) -w -O3 -arch=${ARCH} -o $(OUT_FILE) $(C_FILES) -I. -I.. -I/usr/local/include/ -L/usr/local/lib/ $(FFMPEG_LIBS) -lz -lbz2 -lSDL2  -lmp3lame -lx264 `sdl2-config --cflags --libs`
+	$(CC) -w -O3 -arch=${ARCH} -o $(OUT_DIR)/$(OUT_FILE) $(C_FILES) -I. -I.. -I/usr/local/include/ -L/usr/local/lib/ $(FFMPEG_LIBS) -lz -lbz2 -lSDL2  -lmp3lame -lx264 `sdl2-config --cflags --libs`
 
 build_and_debug:
-	$(CC) -g -w  -arch=${ARCH} -o $(OUT_FILE) $(C_FILES) -I. -I.. -I/usr/local/include/ -L/usr/local/lib/ $(FFMPEG_LIBS) -lz -lbz2 -lSDL2  -lmp3lame -lx264 `sdl2-config --cflags --libs` && \
-	lldb -o run ./$(OUT_FILE) $(TEST_STREAM)
-	lldb ./$(OUT_FILE)
+	$(CC) -g -w  -arch=${ARCH} -o $(OUT_DIR)/$(OUT_FILE) $(C_FILES) -I. -I.. -I/usr/local/include/ -L/usr/local/lib/ $(FFMPEG_LIBS) -lz -lbz2 -lSDL2  -lmp3lame -lx264 `sdl2-config --cflags --libs` && \
+	lldb -o run ./$(OUT_DIR)/$(OUT_FILE) $(TEST_STREAM)
+	lldb ./$(OUT_DIR)/$(OUT_FILE)
 
 test:
-	./$(OUT_FILE) $(TEST_STREAM)
+	./$(OUT_DIR)/$(OUT_FILE) -autoexit -t 10 $(TEST_STREAM)
 
 
 clean:
@@ -73,7 +75,8 @@ WIN_64_OUT_DIR=$(OUT_FILE)_win64
 
 win_64_all:
 	$(MAKE) clean
-	$(MAKE) win_64_check_dependencies
+	$(MAKE) libavutil/ffversion.h
+	$(MAKE) win_64_get_dependencies
 	$(MAKE) win_64_config
 	$(MAKE) win_64_build
 	$(MAKE) win_64_test
@@ -84,23 +87,22 @@ win_64_get_dependencies:
 	mkdir -p $(WIN_64_LIBS_TMP)
 	printf "\nChecking dependencies...\n"
 	if [ ! -x "$$(command -v $(WIN_64_CC))" ];	then echo "$(WIN_64_CC) is reqiured, but it's not installed. Aborting. Dowload and install $(MIN_GW) from https://mingw-w64.org/doku.php/download/mingw-builds and try again."; exit 1; fi && \
+	if [ ! -x "$$(command -v wget)" ];			then echo "wget is reqiured, but it's not installed. Aborting. Install wget and try again."; exit 1; fi && \
 	if [ ! -d $(WIN_64_FFMPEG_SHARED_DIR) ];	then wget $(WIN_64_FFMPEG_SHARED_URL) -O $(WIN_64_LIBS_TMP)/ffmpeg.zip;	unzip $(WIN_64_LIBS_TMP)/ffmpeg.zip -d $(WIN_64_LIBS_BASE);	fi && \
 	if [ ! -d $(WIN_64_SDL_SHARED_DIR) ];		then wget $(WIN_64_SDL_SHARED_URL)    -O $(WIN_64_LIBS_TMP)/sdl.zip;	unzip $(WIN_64_LIBS_TMP)/sdl.zip -d $(WIN_64_LIBS_BASE);		fi && \
 	printf "Dependencies are OK\n"
 
 win_64_config:
 	cd ../ && ./configure  --arch=x86 --target-os=mingw64 --cross-prefix=$(CROSS_PREFIX) --pkg-config=pkg-config $(CONFIG_PARAMS)
+	mkdir -p $(WIN_64_OUT_DIR)
 
 win_64_build:
-	$(CROSS_PREFIX)objdump  -p $(OUT_FILE).exe | grep 'DLL Name:' | sed -e "s/\t*DLL Name: //g"
 	set -e
-	# $(WIN_64_CC) -w -O3 -o $(OUT_FILE) $(C_FILES) -I. -I$(SRC_PATH) -I $(WIN_64_SDL_SHARED_DIR)/$(MIN_GW)/include/SDL2 -L $(WIN_64_SDL_SHARED_DIR)/$(MIN_GW)/lib  -I $(WIN_64_FFMPEG_DIR)/include -L $(WIN_64_FFMPEG_DIR)/lib -I $(WIN_64_MINGW_DIR)/include -L $(WIN_64_MINGW_DIR)/lib      $(FFMPEG_LIBS) -lmingw32 -lSDL2main -lSDL2
-	$(WIN_64_CC) -w -O3 -o $(OUT_FILE) $(C_FILES) -I. -I$(SRC_PATH) -I $(WIN_64_SDL_SHARED_DIR)/$(MIN_GW)/include/SDL2 -L $(WIN_64_SDL_SHARED_DIR)/$(MIN_GW)/lib  -I $(WIN_64_FFMPEG_SHARED_DIR)/include -L $(WIN_64_FFMPEG_SHARED_DIR)/lib -I $(WIN_64_MINGW_DIR)/include -L $(WIN_64_MINGW_DIR)/lib      $(FFMPEG_LIBS) -lmingw32 -lSDL2main -lSDL2
-	mkdir -p $(WIN_64_OUT_DIR)
-	mv -f $(OUT_FILE).exe $(WIN_64_OUT_DIR)
+	$(WIN_64_CC) -w -O3 -o $(WIN_64_OUT_DIR)/$(OUT_FILE) $(C_FILES) -I. -I$(SRC_PATH) -I $(WIN_64_SDL_SHARED_DIR)/$(MIN_GW)/include/SDL2 -L $(WIN_64_SDL_SHARED_DIR)/$(MIN_GW)/lib  -I $(WIN_64_FFMPEG_SHARED_DIR)/include -L $(WIN_64_FFMPEG_SHARED_DIR)/lib -I $(WIN_64_MINGW_DIR)/include -L $(WIN_64_MINGW_DIR)/lib      $(FFMPEG_LIBS) -lmingw32 -lSDL2main -lSDL2
 	find $(WIN_64_FFMPEG_SHARED_DIR) -name "*.dll" -exec cp -n {} $(WIN_64_OUT_DIR) \;
 	find $(WIN_64_SDL_SHARED_DIR) -name "*.dll" -exec cp -n {} $(WIN_64_OUT_DIR) \;
+	$(CROSS_PREFIX)objdump  -p $(WIN_64_OUT_DIR)/$(OUT_FILE).exe | grep 'DLL Name:' | sed -e "s/\t*DLL Name: //g"
 
 
 win_64_test:
-	$(WIN_64_OUT_DIR)/$(OUT_FILE) $(TEST_STREAM)
+	$(WIN_64_OUT_DIR)/$(OUT_FILE).exe  -autoexit -t 10 $(TEST_STREAM)
