fixed windows build

diff --git a/fftools/Makefile_custom b/fftools/Makefile_custom
--- a/fftools/Makefile_custom
+++ b/fftools/Makefile_custom
@@ -29,12 +29,13 @@ NC=\x1b[0m
 RED=\x1b[31;01m
 
 # win compile scripts
-WIN_64_CC=x86_64-w64-mingw32-gcc
-WIN_64_MINGW_DIR="/usr/local/Cellar/mingw-w64/6.0.0_1/toolchain-x86_64/x86_64-w64-mingw32"
-WIN_64_FFMPEG_DIR="../../ffmpeg-4.1.3-win64-dev"
-WIN_64_FFMPEG_SHARED_DIR="../../ffmpeg-4.1.3-win64-shared"
-WIN_64_SDL_DIR="../../SDL2-2.0.9/x86_64-w64-mingw32"
-WIN_64_OUT_DIR="ffpatched_win64"
+MIN_GW=x86_64-w64-mingw32
+CROSS_PREFIX=$(MIN_GW)-
+WIN_64_CC=$(CROSS_PREFIX)gcc
+WIN_64_FFMPEG_DIR=../../ffmpeg-4.1.3-win64-dev
+WIN_64_FFMPEG_SHARED_DIR=../../ffmpeg-4.1.3-win64-shared
+WIN_64_SDL_DIR=../../SDL2-2.0.9/$(MIN_GW)
+WIN_64_OUT_DIR=ffpatched_win64
 
 win_64_all:
 	$(MAKE) clean
@@ -43,16 +44,20 @@ win_64_all:
 	$(MAKE) win_64_build
 
 win_64_check_dependencies:
-	if [ ! -d $(WIN_64_FFMPEG_DIR) ]; then echo "$(RED)fmpeg libs is missing in $(WIN_64_FFMPEG_DIR). Dowload it from https://ffmpeg.zeranoe.com/builds/win32/dev/ffmpeg-4.1.3-win32-dev.zip$(NC)"; exit 1; fi && \
-	if [ ! -d $(WIN_64_FFMPEG_SHARED_DIR) ]; then echo "$(RED)ffmpeg dlls is missing in $(WIN_64_FFMPEG_SHARED_DIR). Dowload it from https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-4.1.3-win64-shared.zip$(NC)"; exit 1; fi && \
-	if [ ! -d $(WIN_64_SDL_DIR) ]; then echo "$(RED)SDL libs is missing in $(WIN_64_SDL_DIR). Dowload it from https://www.libsdl.org/release/SDL2-devel-2.0.9-mingw.tar.gz$(NC)"; exit 1; fi;
+	printf "\nChecking dependencies...\n" && \
+	if [ ! -x "$$(command -v $(WIN_64_CC))" ]; then echo "$(WIN_64_CC) is reqiured, but it's not installed. Aborting. Dowload and install $(MIN_GW) from https://mingw-w64.org/doku.php/download/mingw-builds and try again."; exit 1; fi && \
+	if [ ! -d $(WIN_64_FFMPEG_DIR) ]; then echo "$(RED)fmpeg libs is missing in $(WIN_64_FFMPEG_DIR) . Dowload it from https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-4.1.3-win64-dev.zip$(NC)"; exit 1; fi && \
+	if [ ! -d $(WIN_64_FFMPEG_SHARED_DIR) ]; then echo "$(RED)ffmpeg dlls is missing in $(WIN_64_FFMPEG_SHARED_DIR) . Dowload it from https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-4.1.3-win64-shared.zip$(NC)"; exit 1; fi && \
+	if [ ! -d $(WIN_64_SDL_DIR) ]; then echo "$(RED)SDL libs is missing in $(WIN_64_SDL_DIR) . Dowload it from https://www.libsdl.org/release/SDL2-devel-2.0.9-mingw.tar.gz$(NC)"; exit 1; fi && \
+	printf "Dependencies are OK\n"
 
 win_64_config:
-	cd ../ && ./configure  --arch=x86 --target-os=mingw64 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --enable-gpl --disable-ffmpeg --disable-ffprobe --disable-avdevice --disable-avcodec --disable-avformat --disable-swresample --disable-swscale --disable-postproc --disable-avfilter # --enable-libx264
+	cd ../ && ./configure  --arch=x86 --target-os=mingw64 --cross-prefix=$(CROSS_PREFIX) --pkg-config=pkg-config --enable-gpl --disable-ffmpeg --disable-ffprobe --disable-avdevice --disable-avcodec --disable-avformat --disable-swresample --disable-swscale --disable-postproc --disable-avfilter # --enable-libx264
 
 win_64_build:
-	x86_64-w64-mingw32-objdump  -p ffpatched.exe | grep 'DLL Name:' | sed -e "s/\t*DLL Name: //g"
-	$(WIN_64_CC)  -o ffpatched ffplay.c cmdutils.c -I. -I../ -I$(WIN_64_SDL_DIR)/include/SDL2 -L$(WIN_64_SDL_DIR)/lib  -I$(WIN_64_FFMPEG_DIR)/include -L$(WIN_64_FFMPEG_DIR)/lib -I$(WIN_64_MINGW_DIR)/include -L$(WIN_64_MINGW_DIR)/lib      -lavformat -lavcodec -lavfilter -lavdevice -lavutil -lswresample -lswscale -lmingw32 -lSDL2main -lSDL2
+	$(CROSS_PREFIX)objdump  -p ffpatched.exe | grep 'DLL Name:' | sed -e "s/\t*DLL Name: //g"
+	set -e
+	$(WIN_64_CC) -o ffpatched ffplay.c cmdutils.c -I. -I../ -I$(WIN_64_SDL_DIR)/include/SDL2 -L$(WIN_64_SDL_DIR)/lib  -I$(WIN_64_FFMPEG_DIR)/include -L$(WIN_64_FFMPEG_DIR)/lib -I$(WIN_64_MINGW_DIR)/include -L$(WIN_64_MINGW_DIR)/lib      -lavformat -lavcodec -lavfilter -lavdevice -lavutil -lswresample -lswscale -lmingw32 -lSDL2main -lSDL2
 	mkdir -p $(WIN_64_OUT_DIR)
 	mv -f ffpatched.exe $(WIN_64_OUT_DIR)
 	find $(WIN_64_FFMPEG_SHARED_DIR) -name "*.dll" -exec cp -n {} $(WIN_64_OUT_DIR) \;
